const storeitem=[
    {id:1,price:'1500',weight:'500g',heading:'Pure Desi Ghee',
    text:'Pure desi ghee rich in taste and good for health',
    url:"./images/r-ghee.png"},
    {id:2,price:'120',weight:'450g',heading:'Plain Yougert',
    text:'Plain yougert made by cow milk rich in taste',url:"./images/plain-y450g-r.png"},
    {id:3,price:'1500',weight:'400g',heading:'Sweet Yougert', 
    text:'Sweet yougert rich in taste and good for health',url:"./images/y-400g-r.png"},
    {id:4,price:'1500',weight:'900g',heading:'Plain Yougert',
    text:'Plain yougert made by cow milk rich in taste',url:"./images/y-900g-r.png"},
    {id:5,price:'3500',weight:'2kg',heading:'Shredded Cheese',
    text:'Shredded cheese It is mozzarella / cheddar cheese .A quality product ',url:"./images/s-2kg-r.png"},
    {id:6,price:'1500',weight:'2kg',heading:'Shredded Cheese',
    text:'Shredded cheese It is mozzarella / cheddar cheese .A quality product ',url:"./images/s-cge-r.png"},
    {id:7,price:'1500',weight:'2kg',heading:'Sheredded Mozzaralla',
    text:'Shredded cheese It is mozzarella  cheese .A quality product made by cow milk ',url:"./images/m-che1-r.png"},
    {id:8,price:'1500',weight:'500g',heading:'Pure Ghee',
    text:'Chedder cheese It is  a box packing block cheddar cheese .A quality product ',url:"./images/r-ghee.png"},
    {id:9,price:'1500',weight:'900g',heading:'',
    text:'Shredded cheese It is mozzarella / cheddar cheese .A quality product ',url:"./images/y-900g-r.png"},
    // {id:10,price:'1500',weight:'',heading:'',text:'',url:"./images/"},
    // {id:11,price:'1500',weight:'',heading:'',text:'',url:"./images/"},
    // {id:12,price:'1500',weight:'',heading:'',text:'',url:"./images/"},
 ]
 export default storeitem;